# troubles?

The redis cache in settings.py is set to the ip of the host I was using. Check that.

        "LOCATION": "redis://192.168.88.60:6379/2",

You may need to change this to your host ip.

#

